apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-k8s-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-k8s-demo
    spec:
      containers:
        - name: node-k8s-demo
          image: 577004484740.dkr.ecr.ap-south-1.amazonaws.com/hari/ubuntu:930cccb9746f546ded26f352071a66cf14c9236b
          ports:
            - containerPort: 3000
            
