apiVersion: v1
kind: Service
metadata:
  name: node-k8s-demo
  labels:
    app: node-k8s-demo
spec:
  type: LoadBalancer
  selector:
    app: node-k8s-demo
  ports:
    - protocol: TCP
      port: 80        # external
      targetPort: 3000